#include <iostream>

using namespace std;

int main () {
	
	
	int reportedStudents;
	int soldBoxes, totalBoxes;
	int boxPrice, studentRevenue, totalRevenue;
	
	cout << "####################################\n";
	cout << "Collection for Flood Affected Areas\n";
	cout << "####################################\n\n\n";
	
	cout << "How many students reported for volunteering: ";
	cin >> reportedStudents;
	
	cout << "Enter box price: ";
	cin >> boxPrice;

  
	for (int i =1; i <= reportedStudents; i++) {
		
		cout << "\nEnter number of boxes sold for " << i << " student: ";
		cin >> soldBoxes;
		
		totalBoxes = totalBoxes + soldBoxes; 
		
		studentRevenue = soldBoxes * boxPrice;
		totalRevenue = totalRevenue + studentRevenue;
	}
	
	
	cout << "\n\n\nthe total revenue generated by selling the cookies is " << totalRevenue << endl;
	cout << "\nTotal number of boxes sold are: " << soldBoxes;
	



 return 0;
}
