#include <iostream>

using namespace std;

int main () {
	
	
	int reportedStudents=0, count;
	int soldBoxes=0, totalBoxes=0;
	int boxPrice=0, studentRevenue=0, totalRevenue=0;
	
	cout << "####################################\n";
	cout << "Collection for Flood Affected Areas\n";
	cout << "####################################\n\n\n";
	
	cout << "\nHow many students reported for volunteering: ";
	cin >> reportedStudents;
	
	cout << "\n\nEnter box price: ";
	cin >> boxPrice;

  
	for (count=1; count <= reportedStudents; count++) {
		
		cout << "\nEnter number of boxes sold for " << count << " student: ";
		cin >> soldBoxes;
		
		totalBoxes = totalBoxes + soldBoxes; 
		
		studentRevenue = soldBoxes * boxPrice;
		totalRevenue = totalRevenue + studentRevenue;
	}
	
	
	cout << "\n\n\n Total number of boxes sold are: " << totalBoxes;
	cout << "\n\n The total revenue generated by selling the cookies is " << totalRevenue;
	
	if (reportedStudents !=0) {
		cout << "\n\n The avaerage number of boxes sold by each student is :"<<totalBoxes/ reportedStudents;
	}
	
	



 return 0;
}
